export const mockData = {
  competitions: [
    {
      id: 1,
      title: "National Programming Contest 2024",
      description:
        "A competitive programming contest for students across the nation. Test your algorithmic skills and problem-solving abilities.",
      category: "Programming",
      status: "registration",
      startDate: "2024-03-15",
      endDate: "2024-03-17",
      registrationDeadline: "2024-03-10",
      location: "Tech University Campus",
      teamSize: 3,
      prizePool: "$50,000",
      priority: "high",
      url: "https://nationalcodingcontest.edu",
    },
    {
      id: 2,
      title: "AI Innovation Challenge",
      description:
        "Develop innovative AI solutions for real-world problems. Showcase your machine learning and artificial intelligence expertise.",
      category: "Artificial Intelligence",
      status: "ongoing",
      startDate: "2024-02-20",
      endDate: "2024-04-20",
      registrationDeadline: "2024-02-15",
      location: "Innovation Hub",
      teamSize: 4,
      prizePool: "$75,000",
      priority: "high",
      url: "https://aiinnovationchallenge.org",
    },
    {
      id: 3,
      title: "Cybersecurity Hackathon",
      description:
        "48-hour intensive hackathon focused on cybersecurity challenges. Build secure systems and identify vulnerabilities.",
      category: "Cybersecurity",
      status: "upcoming",
      startDate: "2024-04-05",
      endDate: "2024-04-07",
      registrationDeadline: "2024-03-30",
      location: "Security Institute",
      teamSize: 2,
      prizePool: "$30,000",
      priority: "medium",
      url: "https://cybersecurityhack.net",
    },
    {
      id: 4,
      title: "Data Science Olympics",
      description:
        "Compete in various data science challenges including data analysis, visualization, and predictive modeling.",
      category: "Data Science",
      status: "registration",
      startDate: "2024-05-10",
      endDate: "2024-05-12",
      registrationDeadline: "2024-05-05",
      location: "Data Center Complex",
      teamSize: 3,
      prizePool: "$40,000",
      priority: "high",
      url: "https://datascienceolympics.com",
    },
    {
      id: 5,
      title: "Mobile App Development Contest",
      description:
        "Create innovative mobile applications that solve everyday problems. Focus on user experience and functionality.",
      category: "Mobile Development",
      status: "completed",
      startDate: "2024-01-15",
      endDate: "2024-01-17",
      registrationDeadline: "2024-01-10",
      location: "Mobile Tech Center",
      teamSize: 4,
      prizePool: "$25,000",
      priority: "medium",
      url: "https://mobileappcontest.dev",
    },
    {
      id: 6,
      title: "Web Development Championship",
      description: "Build responsive and interactive web applications using modern frameworks and technologies.",
      category: "Web Development",
      status: "registration",
      startDate: "2024-06-01",
      endDate: "2024-06-03",
      registrationDeadline: "2024-05-25",
      location: "Web Tech Campus",
      teamSize: 3,
      prizePool: "$35,000",
      priority: "medium",
      url: "https://webdevchampionship.io",
    },
  ],

  students: [
    {
      id: 1,
      name: "Alice Johnson",
      email: "alice.johnson@university.edu",
      registrationNo: "CS2021001",
      year: "3rd Year",
      major: "Computer Science",
      registeredAt: "2024-01-15",
    },
    {
      id: 2,
      name: "Bob Smith",
      email: "bob.smith@university.edu",
      registrationNo: "DS2022015",
      year: "2nd Year",
      major: "Data Science",
      registeredAt: "2024-01-20",
    },
    {
      id: 3,
      name: "Carol Davis",
      email: "carol.davis@university.edu",
      registrationNo: "AI2021007",
      year: "4th Year",
      major: "Artificial Intelligence",
      registeredAt: "2024-01-18",
    },
    {
      id: 4,
      name: "David Wilson",
      email: "david.wilson@university.edu",
      registrationNo: "CS2020045",
      year: "4th Year",
      major: "Computer Science",
      registeredAt: "2024-01-22",
    },
    {
      id: 5,
      name: "Emma Brown",
      email: "emma.brown@university.edu",
      registrationNo: "CY2022008",
      year: "2nd Year",
      major: "Cybersecurity",
      registeredAt: "2024-01-25",
    },
    {
      id: 6,
      name: "Frank Miller",
      email: "frank.miller@university.edu",
      registrationNo: "WD2021012",
      year: "3rd Year",
      major: "Web Development",
      registeredAt: "2024-01-28",
    },
    {
      id: 7,
      name: "Grace Lee",
      email: "grace.lee@university.edu",
      registrationNo: "MD2022003",
      year: "1st Year",
      major: "Mobile Development",
      registeredAt: "2024-02-01",
    },
    {
      id: 8,
      name: "Henry Taylor",
      email: "henry.taylor@university.edu",
      registrationNo: "DS2021019",
      year: "3rd Year",
      major: "Data Science",
      registeredAt: "2024-02-05",
    },
  ],

  studentRegistrations: [
    {
      id: 1,
      competitionId: 1,
      competitionTitle: "National Programming Contest 2024",
      studentId: 1,
      teamName: "Code Warriors",
      status: "registered",
      registeredAt: "2024-02-01",
      updatedAt: "2024-02-01",
    },
    {
      id: 2,
      competitionId: 2,
      competitionTitle: "AI Innovation Challenge",
      studentId: 2,
      teamName: "AI Pioneers",
      status: "shortlisted",
      registeredAt: "2024-01-25",
      updatedAt: "2024-02-10",
    },
    {
      id: 3,
      competitionId: 1,
      competitionTitle: "National Programming Contest 2024",
      studentId: 3,
      teamName: "Algorithm Masters",
      status: "registered",
      registeredAt: "2024-02-03",
      updatedAt: "2024-02-03",
    },
    {
      id: 4,
      competitionId: 3,
      competitionTitle: "Cybersecurity Hackathon",
      studentId: 4,
      teamName: "Security Squad",
      status: "registered",
      registeredAt: "2024-02-05",
      updatedAt: "2024-02-05",
    },
    {
      id: 5,
      competitionId: 2,
      competitionTitle: "AI Innovation Challenge",
      studentId: 5,
      teamName: "Neural Networks",
      status: "won",
      registeredAt: "2024-01-28",
      updatedAt: "2024-02-15",
    },
    {
      id: 6,
      competitionId: 4,
      competitionTitle: "Data Science Olympics",
      studentId: 6,
      teamName: "Data Wizards",
      status: "registered",
      registeredAt: "2024-02-08",
      updatedAt: "2024-02-08",
    },
    {
      id: 7,
      competitionId: 5,
      competitionTitle: "Mobile App Development Contest",
      studentId: 7,
      teamName: "App Innovators",
      status: "shortlisted",
      registeredAt: "2024-01-12",
      updatedAt: "2024-01-20",
    },
    {
      id: 8,
      competitionId: 6,
      competitionTitle: "Web Development Championship",
      studentId: 8,
      teamName: "Web Builders",
      status: "registered",
      registeredAt: "2024-02-10",
      updatedAt: "2024-02-10",
    },
  ],

  teams: [
    {
      id: 1,
      name: "Code Warriors",
      competitionId: 1,
      competitionTitle: "National Programming Contest 2024",
      members: [
        { id: 1, name: "Alice Johnson", role: "Team Lead", registrationNo: "CS2021001" },
        { id: 9, name: "John Doe", role: "Developer", registrationNo: "CS2021002" },
        { id: 10, name: "Jane Smith", role: "Analyst", registrationNo: "CS2021003" },
      ],
      status: "active",
      createdAt: "2024-02-01",
      lastActivity: "2024-02-15",
    },
    {
      id: 2,
      name: "AI Pioneers",
      competitionId: 2,
      competitionTitle: "AI Innovation Challenge",
      members: [
        { id: 2, name: "Bob Smith", role: "Team Lead", registrationNo: "DS2022015" },
        { id: 11, name: "Sarah Wilson", role: "ML Engineer", registrationNo: "AI2022001" },
        { id: 12, name: "Mike Johnson", role: "Data Scientist", registrationNo: "DS2022016" },
        { id: 13, name: "Lisa Brown", role: "Research Analyst", registrationNo: "AI2022002" },
      ],
      status: "shortlisted",
      createdAt: "2024-01-25",
      lastActivity: "2024-02-18",
    },
    {
      id: 3,
      name: "Security Squad",
      competitionId: 3,
      competitionTitle: "Cybersecurity Hackathon",
      members: [
        { id: 4, name: "David Wilson", role: "Team Lead", registrationNo: "CS2020045" },
        { id: 14, name: "Alex Chen", role: "Security Analyst", registrationNo: "CY2022009" },
      ],
      status: "active",
      createdAt: "2024-02-05",
      lastActivity: "2024-02-12",
    },
    {
      id: 4,
      name: "Neural Networks",
      competitionId: 2,
      competitionTitle: "AI Innovation Challenge",
      members: [
        { id: 5, name: "Emma Brown", role: "Team Lead", registrationNo: "CY2022008" },
        { id: 15, name: "Tom Davis", role: "AI Developer", registrationNo: "AI2021008" },
        { id: 16, name: "Amy White", role: "Data Engineer", registrationNo: "DS2021020" },
        { id: 17, name: "Chris Green", role: "ML Researcher", registrationNo: "AI2021009" },
      ],
      status: "winner",
      createdAt: "2024-01-28",
      lastActivity: "2024-02-20",
    },
  ],
}
