export const mockData = {
  user: {
    id: 1,
    name: "John Doe",
    email: "john.doe@university.edu",
    institution: "Tech University",
    year: "3rd Year",
    major: "Computer Science",
  },

  competitions: [
    {
      id: 1,
      title: "AI Innovation Challenge 2024",
      description:
        "Build innovative AI solutions to solve real-world problems. This competition focuses on machine learning, natural language processing, and computer vision applications.",
      category: "Artificial Intelligence",
      status: "registration",
      startDate: "2024-02-15",
      endDate: "2024-02-17",
      registrationDeadline: "2024-02-10",
      location: "Tech Hub, Silicon Valley",
      teamSize: 4,
      prizePool: "$50,000",
      priority: "high",
      requirements: [
        "Must be currently enrolled students",
        "Team of 4 members required",
        "Basic knowledge of Python and ML frameworks",
        "Laptop with development environment setup",
      ],
    },
    {
      id: 2,
      title: "Web Development Hackathon",
      description:
        "Create amazing web applications using modern frameworks and technologies. Focus on user experience, performance, and innovative features.",
      category: "Web Development",
      status: "upcoming",
      startDate: "2024-03-01",
      endDate: "2024-03-03",
      registrationDeadline: "2024-02-25",
      location: "Innovation Center, Austin",
      teamSize: 3,
      prizePool: "$25,000",
      priority: "medium",
    },
    {
      id: 3,
      title: "Cybersecurity CTF Championship",
      description:
        "Test your cybersecurity skills in this capture-the-flag competition. Solve challenges in cryptography, web security, reverse engineering, and more.",
      category: "Cybersecurity",
      status: "ongoing",
      startDate: "2024-01-20",
      endDate: "2024-01-22",
      registrationDeadline: "2024-01-15",
      location: "Security Institute, Boston",
      teamSize: 2,
      prizePool: "$30,000",
      priority: "high",
    },
    {
      id: 4,
      title: "Mobile App Development Contest",
      description:
        "Design and develop innovative mobile applications for iOS and Android platforms. Focus on user interface, functionality, and market potential.",
      category: "Mobile Development",
      status: "registration",
      startDate: "2024-04-10",
      endDate: "2024-04-12",
      registrationDeadline: "2024-04-05",
      location: "Mobile Tech Center, Seattle",
      teamSize: 3,
      prizePool: "$35,000",
      priority: "medium",
    },
    {
      id: 5,
      title: "Data Science Olympics",
      description:
        "Analyze complex datasets and build predictive models to solve business problems. Competition includes data cleaning, visualization, and machine learning challenges.",
      category: "Data Science",
      status: "upcoming",
      startDate: "2024-05-15",
      endDate: "2024-05-17",
      registrationDeadline: "2024-05-10",
      location: "Data Analytics Hub, Chicago",
      teamSize: 4,
      prizePool: "$40,000",
      priority: "high",
    },
    {
      id: 6,
      title: "Blockchain Innovation Summit",
      description:
        "Develop blockchain-based solutions for various industries. Focus on smart contracts, DeFi applications, and cryptocurrency technologies.",
      category: "Blockchain",
      status: "registration",
      startDate: "2024-06-20",
      endDate: "2024-06-22",
      registrationDeadline: "2024-06-15",
      location: "Crypto Valley, Miami",
      teamSize: 3,
      prizePool: "$45,000",
      priority: "low",
    },
  ],

  registeredCompetitions: [
    {
      id: 1,
      title: "AI Innovation Challenge 2024",
      description: "Build innovative AI solutions to solve real-world problems.",
      category: "Artificial Intelligence",
      status: "registration",
      startDate: "2024-02-15",
      endDate: "2024-02-17",
      registrationDeadline: "2024-02-10",
      location: "Tech Hub, Silicon Valley",
      teamSize: 4,
      prizePool: "$50,000",
      priority: "high",
    },
    {
      id: 4,
      title: "Mobile App Development Contest",
      description: "Design and develop innovative mobile applications.",
      category: "Mobile Development",
      status: "upcoming",
      startDate: "2024-04-10",
      endDate: "2024-04-12",
      registrationDeadline: "2024-04-05",
      location: "Mobile Tech Center, Seattle",
      teamSize: 3,
      prizePool: "$35,000",
      priority: "medium",
    },
  ],

  userTeams: [
    {
      id: 1,
      name: "AI Innovators",
      competition: "AI Innovation Challenge 2024",
      role: "Team Leader",
      members: ["John Doe", "Alice Smith", "Bob Johnson", "Carol Williams"],
      status: "active",
      createdDate: "2024-01-15",
    },
    {
      id: 2,
      name: "Mobile Masters",
      competition: "Mobile App Development Contest",
      role: "Developer",
      members: ["John Doe", "David Brown", "Emma Davis"],
      status: "active",
      createdDate: "2024-01-20",
    },
  ],
}
