export const mockData = {
  user: {
    id: 1,
    name: "John Doe",
    email: "john.doe@university.edu",
    registrationNo: "CS2021001",
    year: "3rd Year",
    major: "Computer Science",
  },

  competitions: [
    {
      id: 1,
      title: "AI Innovation Challenge 2024",
      description:
        "Build innovative AI solutions to solve real-world problems. This competition focuses on machine learning, natural language processing, and computer vision applications.",
      category: "Artificial Intelligence",
      status: "registration",
      startDate: "2024-02-15",
      endDate: "2024-02-17",
      registrationDeadline: "2024-02-10",
      location: "Tech Hub, Silicon Valley",
      teamSize: 4,
      prizePool: "$50,000",
      priority: "high",
      url: "https://ai-innovation-challenge.com",
      requirements: [
        "Must be currently enrolled students",
        "Team of 4 members required",
        "Basic knowledge of Python and ML frameworks",
        "Laptop with development environment setup",
      ],
    },
    {
      id: 2,
      title: "Web Development Hackathon",
      description:
        "Create amazing web applications using modern frameworks and technologies. Focus on user experience, performance, and innovative features.",
      category: "Web Development",
      status: "upcoming",
      startDate: "2024-03-01",
      endDate: "2024-03-03",
      registrationDeadline: "2024-02-25",
      location: "Innovation Center, Austin",
      teamSize: 3,
      prizePool: "$25,000",
      priority: "medium",
      url: "https://webdev-hackathon.org",
    },
    {
      id: 3,
      title: "Cybersecurity CTF Championship",
      description:
        "Test your cybersecurity skills in this capture-the-flag competition. Solve challenges in cryptography, web security, reverse engineering, and more.",
      category: "Cybersecurity",
      status: "ongoing",
      startDate: "2024-01-20",
      endDate: "2024-01-22",
      registrationDeadline: "2024-01-15",
      location: "Security Institute, Boston",
      teamSize: 2,
      prizePool: "$30,000",
      priority: "high",
      url: "https://cybersec-ctf.net",
    },
    {
      id: 4,
      title: "Mobile App Development Contest",
      description:
        "Design and develop innovative mobile applications for iOS and Android platforms. Focus on user interface, functionality, and market potential.",
      category: "Mobile Development",
      status: "registration",
      startDate: "2024-04-10",
      endDate: "2024-04-12",
      registrationDeadline: "2024-04-05",
      location: "Mobile Tech Center, Seattle",
      teamSize: 3,
      prizePool: "$35,000",
      priority: "medium",
      url: "https://mobile-app-contest.com",
    },
    {
      id: 5,
      title: "Data Science Olympics",
      description:
        "Analyze complex datasets and build predictive models to solve business problems. Competition includes data cleaning, visualization, and machine learning challenges.",
      category: "Data Science",
      status: "upcoming",
      startDate: "2024-05-15",
      endDate: "2024-05-17",
      registrationDeadline: "2024-05-10",
      location: "Data Analytics Hub, Chicago",
      teamSize: 4,
      prizePool: "$40,000",
      priority: "high",
      url: "https://datascience-olympics.org",
    },
    {
      id: 6,
      title: "Blockchain Innovation Summit",
      description:
        "Develop blockchain-based solutions for various industries. Focus on smart contracts, DeFi applications, and cryptocurrency technologies.",
      category: "Blockchain",
      status: "registration",
      startDate: "2024-06-20",
      endDate: "2024-06-22",
      registrationDeadline: "2024-06-15",
      location: "Crypto Valley, Miami",
      teamSize: 3,
      prizePool: "$45,000",
      priority: "low",
      url: "https://blockchain-summit.io",
    },
  ],

  students: [
    {
      id: 1,
      name: "John Doe",
      email: "john.doe@university.edu",
      registrationNo: "CS2021001",
      year: "3rd Year",
      major: "Computer Science",
      registeredAt: "2024-01-15",
    },
    {
      id: 2,
      name: "Alice Smith",
      email: "alice.smith@university.edu",
      registrationNo: "DS2022015",
      year: "2nd Year",
      major: "Data Science",
      registeredAt: "2024-01-16",
    },
    {
      id: 3,
      name: "Bob Johnson",
      email: "bob.johnson@university.edu",
      registrationNo: "SE2020045",
      year: "4th Year",
      major: "Software Engineering",
      registeredAt: "2024-01-17",
    },
    {
      id: 4,
      name: "Carol Williams",
      email: "carol.williams@university.edu",
      registrationNo: "CY2021032",
      year: "3rd Year",
      major: "Cybersecurity",
      registeredAt: "2024-01-18",
    },
    {
      id: 5,
      name: "David Brown",
      email: "david.brown@university.edu",
      registrationNo: "MD2022008",
      year: "2nd Year",
      major: "Mobile Development",
      registeredAt: "2024-01-19",
    },
  ],

  studentRegistrations: [
    {
      id: 1,
      competitionId: 1,
      competitionTitle: "AI Innovation Challenge 2024",
      teamName: "AI Innovators",
      teamMembers: ["John Doe", "Alice Smith", "Bob Johnson", "Carol Williams"],
      status: "shortlisted",
      registrationDate: "2024-01-15",
      location: "Tech Hub, Silicon Valley",
      proofDocument: "shortlist_certificate.pdf",
      updatedAt: "2024-01-25T10:30:00Z",
    },
    {
      id: 2,
      competitionId: 4,
      competitionTitle: "Mobile App Development Contest",
      teamName: "Mobile Masters",
      teamMembers: ["John Doe", "David Brown", "Alice Smith"],
      status: "won",
      registrationDate: "2024-01-20",
      location: "Mobile Tech Center, Seattle",
      proofDocument: "winner_certificate.pdf",
      updatedAt: "2024-01-28T14:15:00Z",
    },
    {
      id: 3,
      competitionId: 2,
      competitionTitle: "Web Development Hackathon",
      teamName: "Web Warriors",
      teamMembers: ["Bob Johnson", "Carol Williams", "David Brown"],
      status: "registered",
      registrationDate: "2024-01-22",
      location: "Innovation Center, Austin",
      updatedAt: "2024-01-22T09:00:00Z",
    },
    {
      id: 4,
      competitionId: 3,
      competitionTitle: "Cybersecurity CTF Championship",
      teamName: "Cyber Defenders",
      teamMembers: ["Carol Williams", "Alice Smith"],
      status: "shortlisted",
      registrationDate: "2024-01-18",
      location: "Security Institute, Boston",
      updatedAt: "2024-01-26T16:45:00Z",
    },
    {
      id: 5,
      competitionId: 5,
      competitionTitle: "Data Science Olympics",
      teamName: "Data Dynamos",
      teamMembers: ["Alice Smith", "John Doe", "Bob Johnson", "David Brown"],
      status: "registered",
      registrationDate: "2024-01-24",
      location: "Data Analytics Hub, Chicago",
      updatedAt: "2024-01-24T11:20:00Z",
    },
  ],

  userTeams: [
    {
      id: 1,
      name: "AI Innovators",
      competition: "AI Innovation Challenge 2024",
      role: "Team Leader",
      members: ["John Doe", "Alice Smith", "Bob Johnson", "Carol Williams"],
      status: "active",
      createdDate: "2024-01-15",
      description:
        "A passionate team focused on developing innovative AI solutions for real-world problems. We specialize in machine learning and natural language processing.",
    },
    {
      id: 2,
      name: "Mobile Masters",
      competition: "Mobile App Development Contest",
      role: "Developer",
      members: ["John Doe", "David Brown", "Alice Smith"],
      status: "active",
      createdDate: "2024-01-20",
      description: "Expert mobile developers creating cutting-edge applications for iOS and Android platforms.",
    },
    {
      id: 3,
      name: "Web Warriors",
      competition: "Web Development Hackathon",
      role: "Team Leader",
      members: ["John Doe", "Emma Davis", "Michael Wilson"],
      status: "active",
      createdDate: "2024-01-25",
      description:
        "Full-stack web developers building modern, responsive web applications with the latest technologies.",
    },
  ],
}
